### PR TITLE
Added reference to OpsTools-ansible

### PR DESCRIPTION
**Pull request by it-praktyk**
cc: @mrunge, @paramite

### CODE REVIEW

**Comment by mrunge** [comment]
More info can be found here: 

- https://wiki.centos.org/SpecialInterestGroup/OpsTools

- https://github.com/centos-opstools/opstools-doc

**Comment by it-praktyk** [comment]
Thx, @mrunge - I just added a reference to CentOS SIG OpsTools to my previous PR.

**Comment by it-praktyk** [comment]
@mrunge, when can I open the issue for ansible-opstools? I see some inconsistency in documentation and I've some additional remarks.

**Comment by mrunge** [comment]
Please submit patches. We're happy to take them! For contribution, we're using git review for submitting patches for review. The process used is quite comparable to https://docs.openstack.org/contributor-guide/quickstart/first-timers.html#committing-a-change , our review portal can be found at  https://review.rdoproject.org/r/#/q/status:open

**Comment by jdauphant** [comment]
Thanks.
I will take a look to the project when I got time

**Comment by jdauphant** [comment]
@it-praktyk Thanks sorry for the delay

**Pull request merged**
