### PR TITLE
add videos and correct markdown formatting

### PR DESCRIPTION
**Pull request by TylerNakamura**

### CODE REVIEW

**Comment by jdauphant** [comment]
@TylerNakamura Thanks for the cleanup and all the work to find videos.
I see there are 4-5 videos for introduction of Ansible (and some other videos may have the same content). It could be confusing for people to know where to start, we can made a subselection of the best videos, what do you think ?

**Comment by TylerNakamura** [comment]
@jdauphant hmmm interesting idea. Typically with the videos I prefer to just play them all in the background while I am doing other tasks, so redundant content isn't a big deal for me.
My hesitation in creating a "best" section is perhaps that the content may become outdated, or biased. In addition to that, I don't consider myself to be knowledgable enough with Ansible to discern the best among these videos.
What about perhaps bolding the links that we find best? For example, there is a talk in there from the actual creator of Ansible that is definitely worthy of a bold link. The links will all remain in the "videos" section in chronological order, but only the "best" videos would be bolded (or starred, or italicized).
Thoughts?

**Comment by jdauphant** [comment]
I was more thinking to only put the best video and remove the outdated. The objective of the list is to always up to date curated resources

**Comment by jdauphant** [comment]
Closed and restarted from #36

**Pull request closed without merging**
