### PR TITLE
Added Ansigenome

### PR DESCRIPTION
**Pull request by it-praktyk**

### CODE REVIEW

**Comment by it-praktyk** [comment]
cc: @nickjj

**Comment by nickjj** [comment]
Hey, thanks for adding Ansigenome to the list, I really appreciate it.

**Comment by it-praktyk** [comment]
@dmsimard, [twitted](https://twitter.com/dmsimard/status/915986446154002432) about your project. Thanks David!

**Comment by jdauphant** [comment]
@it-praktyk @nickjj Nice project, thanks for the contribution ;)

**Pull request merged**
