### PR TITLE
DebOps added to playbooks

### PR DESCRIPTION
**Pull request by it-praktyk**
CC: @drybjed , @ganto , @nickjj , @scibi , @ypid

### CODE REVIEW

**Comment by jdauphant** [comment]
@it-praktyk Thanks for the suggestion. 
The project have lots of dependencies, it will take a little time to review it before integrate it to the list

**Comment by ypid** [comment]
Thanks for CC-ing. Awesome list, I did not know it before :+1:

@jdauphant If you have any question, let us know :)

**Comment by nickjj** [comment]
Thanks for including it into the list. @jdauphant you might want to begin by skimming https://docs.debops.org/en/latest/.

**Comment by jdauphant** [comment]
I just finish read the doc and I have took a look at the code. 
It's an interesting approach, good continuation on the project!

**Comment by jdauphant** [comment]
Could be complicated, I host most of my stuffs on FreeBSD, have you plan to support it ? :-)

**Comment by drybjed** [comment]
@jdauphant I don't think that will be feasible any time soon. But you can always launch a Debian VM, or rent a VPS somewhere to try it. ;-)

**Comment by jdauphant** [comment]
If I had illimited time in the world, I will have try but we have to make choice.
I no longer have computer to manage except my personnal computer (that is managed by Ansible by the way)

**Pull request merged**
